packages:
  - apps/*

catalog:
  '@antfu/eslint-config': ^4.12.0
  '@iconify-json/lucide': ^1.2.37
  '@iconify-json/simple-icons': ^1.2.32
  '@nuxt/eslint': ^1.3.0
  '@nuxt/ui': ^3.0.2
  eslint: ^9.24.0
  eslint-plugin-format: ^1.0.1
  nuxt: ^3.16.2
  prettier: ^3.5.3
  prettier-plugin-tailwindcss: ^0.6.11
  typescript: ^5.8.3

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - vue-demi
